-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#141318',
  base01 = '#0e0e13',
  base02 = '#1c1b20',
  base03 = '#47464f',
  base04 = '#c9c5d0',
  base05 = '#e5e1e9',
  base06 = '#313036',
  base07 = '#3a383e',

  base08 = '#ffb4ab',
  base09 = '#ecb8ce',
  base0A = '#c8c3dc',
  base0B = '#c7bfff',
  base0C = '#613b4d',
  base0D = '#463f77',
  base0E = '#474459',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#463f77',
  fg = '#141318',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#ffd8e8',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#ecb8ce',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#c8c3dc',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#5e5791',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#0e0e13',
  fg = '#c7bfff',
})
